project:
  type: book
  output-dir: _book

book:
  title: "Deep Learning Foundations"
  author: "Pawan Rama Mali"
  date: "2024"
  chapters:
    - index.qmd
    - chapters/01-math-foundations.qmd
  
format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt

bibliography: references.bib